# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_oursins.ui'
#
# Created: Sat Nov  8 20:44:55 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Oursins(object):
    def setupUi(self, Oursins):
        Oursins.setObjectName(_fromUtf8("Oursins"))
        Oursins.resize(521, 539)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Oursins.sizePolicy().hasHeightForWidth())
        Oursins.setSizePolicy(sizePolicy)
        Oursins.setMinimumSize(QtCore.QSize(521, 539))
        Oursins.setMaximumSize(QtCore.QSize(521, 539))
        self.buttonBox = QtGui.QDialogButtonBox(Oursins)
        self.buttonBox.setGeometry(QtCore.QRect(170, 500, 341, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.frame = QtGui.QFrame(Oursins)
        self.frame.setGeometry(QtCore.QRect(10, 10, 501, 141))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 481, 122))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_8.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_8.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_8.addWidget(self.label_12)
        self.label_13 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_8.addWidget(self.label_13)
        self.horizontalLayout_13.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.inputFlowTable = QtGui.QComboBox(self.horizontalLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputFlowTable.sizePolicy().hasHeightForWidth())
        self.inputFlowTable.setSizePolicy(sizePolicy)
        self.inputFlowTable.setObjectName(_fromUtf8("inputFlowTable"))
        self.verticalLayout_9.addWidget(self.inputFlowTable)
        self.originVar = QtGui.QComboBox(self.horizontalLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.originVar.sizePolicy().hasHeightForWidth())
        self.originVar.setSizePolicy(sizePolicy)
        self.originVar.setObjectName(_fromUtf8("originVar"))
        self.verticalLayout_9.addWidget(self.originVar)
        self.destinationVar = QtGui.QComboBox(self.horizontalLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.destinationVar.sizePolicy().hasHeightForWidth())
        self.destinationVar.setSizePolicy(sizePolicy)
        self.destinationVar.setObjectName(_fromUtf8("destinationVar"))
        self.verticalLayout_9.addWidget(self.destinationVar)
        self.flowValue = QtGui.QComboBox(self.horizontalLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flowValue.sizePolicy().hasHeightForWidth())
        self.flowValue.setSizePolicy(sizePolicy)
        self.flowValue.setObjectName(_fromUtf8("flowValue"))
        self.verticalLayout_9.addWidget(self.flowValue)
        self.horizontalLayout_13.addLayout(self.verticalLayout_9)
        self.frame_2 = QtGui.QFrame(Oursins)
        self.frame_2.setGeometry(QtCore.QRect(10, 160, 501, 101))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayoutWidget_9 = QtGui.QWidget(self.frame_2)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(10, 10, 481, 85))
        self.verticalLayoutWidget_9.setObjectName(_fromUtf8("verticalLayoutWidget_9"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_12.addWidget(self.label_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget_9)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_9)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.inputLayers = QtGui.QComboBox(self.verticalLayoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputLayers.sizePolicy().hasHeightForWidth())
        self.inputLayers.setSizePolicy(sizePolicy)
        self.inputLayers.setObjectName(_fromUtf8("inputLayers"))
        self.verticalLayout_11.addWidget(self.inputLayers)
        self.geographicVar = QtGui.QComboBox(self.verticalLayoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geographicVar.sizePolicy().hasHeightForWidth())
        self.geographicVar.setSizePolicy(sizePolicy)
        self.geographicVar.setObjectName(_fromUtf8("geographicVar"))
        self.verticalLayout_11.addWidget(self.geographicVar)
        self.horizontalLayout_6.addLayout(self.verticalLayout_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.frame_3 = QtGui.QFrame(Oursins)
        self.frame_3.setGeometry(QtCore.QRect(10, 360, 501, 141))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.frame_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 481, 121))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_15 = QtGui.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_3.addWidget(self.label_15)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.memoryLayerOutput = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.memoryLayerOutput.setChecked(True)
        self.memoryLayerOutput.setObjectName(_fromUtf8("memoryLayerOutput"))
        self.horizontalLayout_9.addWidget(self.memoryLayerOutput)
        self.shapefileOutput = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.shapefileOutput.setChecked(False)
        self.shapefileOutput.setObjectName(_fromUtf8("shapefileOutput"))
        self.horizontalLayout_9.addWidget(self.shapefileOutput)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setEnabled(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_10.addWidget(self.label_4)
        self.horizontalLayout_10.addLayout(self.verticalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.outputFilename = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.outputFilename.setEnabled(False)
        self.outputFilename.setReadOnly(True)
        self.outputFilename.setObjectName(_fromUtf8("outputFilename"))
        self.horizontalLayout_3.addWidget(self.outputFilename)
        self.selectFilename = QtGui.QToolButton(self.verticalLayoutWidget_3)
        self.selectFilename.setEnabled(False)
        self.selectFilename.setObjectName(_fromUtf8("selectFilename"))
        self.horizontalLayout_3.addWidget(self.selectFilename)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.addToCanevas = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.addToCanevas.setEnabled(False)
        self.addToCanevas.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.addToCanevas.setChecked(True)
        self.addToCanevas.setObjectName(_fromUtf8("addToCanevas"))
        self.verticalLayout_3.addWidget(self.addToCanevas)
        self.frame_5 = QtGui.QFrame(Oursins)
        self.frame_5.setGeometry(QtCore.QRect(10, 270, 501, 80))
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.frame_5)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 491, 61))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_7.addWidget(self.label_3)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.label_17.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_12.addWidget(self.label_17)
        self.minValue = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_6)
        self.minValue.setEnabled(True)
        self.minValue.setDecimals(3)
        self.minValue.setMaximum(999999999.0)
        self.minValue.setObjectName(_fromUtf8("minValue"))
        self.horizontalLayout_12.addWidget(self.minValue)
        self.label_18 = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.label_18.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_12.addWidget(self.label_18)
        self.maxDist = QtGui.QSpinBox(self.verticalLayoutWidget_6)
        self.maxDist.setEnabled(True)
        self.maxDist.setMaximum(999999999)
        self.maxDist.setObjectName(_fromUtf8("maxDist"))
        self.horizontalLayout_12.addWidget(self.maxDist)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)

        self.retranslateUi(Oursins)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Oursins.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Oursins.reject)
        QtCore.QMetaObject.connectSlotsByName(Oursins)

    def retranslateUi(self, Oursins):
        Oursins.setWindowTitle(_translate("Oursins", "Flow map (Oursins)", None))
        self.label_10.setText(_translate("Oursins", "Flow table", None))
        self.label_11.setText(_translate("Oursins", "Origin", None))
        self.label_12.setText(_translate("Oursins", "Destination", None))
        self.label_13.setText(_translate("Oursins", "Value", None))
        self.label_7.setText(_translate("Oursins", "Extract coordinates from a layer", None))
        self.label.setText(_translate("Oursins", "layer", None))
        self.label_2.setText(_translate("Oursins", "Geographic ID", None))
        self.label_15.setText(_translate("Oursins", "Output :", None))
        self.memoryLayerOutput.setText(_translate("Oursins", "Memory", None))
        self.shapefileOutput.setText(_translate("Oursins", "Shapefile", None))
        self.label_4.setText(_translate("Oursins", "File name", None))
        self.selectFilename.setText(_translate("Oursins", "...", None))
        self.addToCanevas.setText(_translate("Oursins", "add to the canvas", None))
        self.label_3.setText(_translate("Oursins", "Filters", None))
        self.label_17.setText(_translate("Oursins", "Min value", None))
        self.label_18.setText(_translate("Oursins", "Max distance (km)", None))

